# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Funding Call"
    url: omaib
    parent: "About"
    weight: 5

  - name: MultimodalAIForum'26
    url: multimodalai-forum26
    weight: 10

  - name: MultimodalAI'26
    url: multimodalai26
    weight: 15

  - name: "About"
    url: "#"
    weight: 20

  - name: "Resources"
    url: "#"
    weight: 30

  - name: "Landscape Explorer"
    parent: "Resources" # Parent name must match exactly
    url: https://multimodalai.github.io/multimodal-ai-landscape/
    weight: 1

  - name: "YouTube"
    parent: "Resources" # Parent name must match exactly
    url: https://www.youtube.com/@UKMultimodalAI
    weight: 2

  - name: "Past Events"
    url: "#"
    weight: 40

  - name: "Code of Conduct"
    url: code-of-conduct
    parent: "About"
    weight: 50

  - name: "MultimodalAI'25"
    parent: "Past Events" # Parent name must match exactly
    url: multimodalai25
    weight: 1

  - name: "MultimodalAI'25 Hackathon"
    parent: "Past Events" # Parent name must match exactly
    url: multimodalai25/hackathon/
    weight: 2

  - name: "EMBC'25Workshop"
    parent: "Past Events" # Parent name must match exactly
    url: embc25workshop
    weight: 3

  - name: "MultimodalAI'24"
    parent: "Past Events" # Parent name must match exactly
    url: multimodalai24
    weight: 4

  - name: "MultimodalAIForum'24"
    parent: "Past Events" # Parent name must match exactly
    url: multimodalai-forum24
    weight: 5

  - name: "MultimodalAISprint'23"
    parent: "Past Events" # Parent name must match exactly
    url: multimodalai-sprint23
    weight: 6

  - name: "MultimodalAI'23"
    parent: "Past Events" # Parent name must match exactly
    url: multimodalai23
    weight: 7

  - name: "UKOMAIN"
    parent: "About" # Parent name must match exactly
    url: "#ukomain"
    weight: 1

  - name: "Team"
    parent: "About" # Parent name must match exactly
    url: "#team"
    weight: 2

  - name: "Contact"
    parent: "About" # Parent name must match exactly
    url: "#contact"
    weight: 3
